/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package johan_sanjaya_181011401366_uas;

import HitungFuzzy1.HitungFuzzy1;
import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class MainView1 extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        permintaan = new javax.swing.JLabel();
        Johan_VariabelTanggal = new javax.swing.JComboBox<>();
        Johan_VariabelJenisObat = new javax.swing.JComboBox<>();
        Johan_VariabelPermintaan = new javax.swing.JTextField();
        Johan_VariabelPersediaan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Johan_VariabelBtnPrediksi = new javax.swing.JButton();
        Johan_VariabelReset = new javax.swing.JButton();
        Johan_VariabelPrediksi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        persediaan = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Prediksi Produksi Obat Flu");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Program Prediksi Produksi Obat Flu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jLabel1.setText("Panel Prediksi");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Jenis Obat");

        permintaan.setText("Permintaan");

        Johan_VariabelTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/05/21", "08/05/21", "16/05/21", "25/05/21" }));
        Johan_VariabelTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Johan_VariabelTanggalActionPerformed(evt);
            }
        });

        Johan_VariabelJenisObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obat FLu" }));

        Johan_VariabelPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Johan_VariabelPermintaanActionPerformed(evt);
            }
        });

        Johan_VariabelPersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Johan_VariabelPersediaanActionPerformed(evt);
            }
        });

        jLabel6.setText("200 s/d 541");

        jLabel7.setText("132 s/d 196");

        jLabel8.setText("Tahun 2021");

        Johan_VariabelBtnPrediksi.setText("Prediksi");
        Johan_VariabelBtnPrediksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Johan_VariabelBtnPrediksiActionPerformed(evt);
            }
        });

        Johan_VariabelReset.setText("Reset");
        Johan_VariabelReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Johan_VariabelResetActionPerformed(evt);
            }
        });

        Johan_VariabelPrediksi.setText("Prediksi produksi : ");

        jLabel11.setText("Johan Sanjaya 181011401366");

        persediaan.setText("Persediaan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(permintaan)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(persediaan))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Johan_VariabelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Johan_VariabelJenisObat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Johan_VariabelPermintaan)
                                    .addComponent(Johan_VariabelPersediaan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Johan_VariabelPrediksi)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Johan_VariabelBtnPrediksi)
                        .addGap(18, 18, 18)
                        .addComponent(Johan_VariabelReset)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Johan_VariabelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Johan_VariabelJenisObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permintaan)
                    .addComponent(Johan_VariabelPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Johan_VariabelPersediaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(persediaan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Johan_VariabelBtnPrediksi)
                    .addComponent(Johan_VariabelReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Johan_VariabelPrediksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Johan_VariabelTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Johan_VariabelTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Johan_VariabelTanggalActionPerformed

    private void Johan_VariabelResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Johan_VariabelResetActionPerformed
        Johan_VariabelPersediaan.setText(null);
        Johan_VariabelPermintaan.setText(null);
    }//GEN-LAST:event_Johan_VariabelResetActionPerformed

    private void Johan_VariabelBtnPrediksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Johan_VariabelBtnPrediksiActionPerformed
        double hasil;
        HitungFuzzy1 hf=new HitungFuzzy1();
        hasil = hf.PerkiraanProduksi(Double.parseDouble(Johan_VariabelPersediaan.getText()),
        Double.parseDouble(Johan_VariabelPermintaan.getText()));
        long hasilPrediksi=(long)(hasil);
        String pesan="Prediksi produksi obat flu adalah :"+hasilPrediksi+",-";
        Johan_VariabelPrediksi.setText("Prediksi produksi adalah "+hasilPrediksi+" Strip");
        
    }//GEN-LAST:event_Johan_VariabelBtnPrediksiActionPerformed

    private void Johan_VariabelPersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Johan_VariabelPersediaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Johan_VariabelPersediaanActionPerformed

    private void Johan_VariabelPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Johan_VariabelPermintaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Johan_VariabelPermintaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Johan_VariabelBtnPrediksi;
    private javax.swing.JComboBox<String> Johan_VariabelJenisObat;
    private javax.swing.JTextField Johan_VariabelPermintaan;
    private javax.swing.JTextField Johan_VariabelPersediaan;
    private javax.swing.JLabel Johan_VariabelPrediksi;
    private javax.swing.JButton Johan_VariabelReset;
    private javax.swing.JComboBox<String> Johan_VariabelTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel permintaan;
    private javax.swing.JLabel persediaan;
    // End of variables declaration//GEN-END:variables
}
